### ISSUE TITLE
Suggestion: Rename to do_contains

### ISSUE THREAD

**Issue by micahkendall** [logicalmechanism/assist#31]
https://github.com/logicalmechanism/assist/blob/c6c55e64d997f90814ec51aa0632e183a4da9ec9/lib/assist/values.ak#L59C30-L59C30

**Comment by micahkendall** [comment]
do_contains is in line with stdlib helpers for this kind

**Comment by logicalmechanism** [comment]
Good catch and suggestion. There are many other helper functions to update too.

**Comment by logicalmechanism** [comment]
All pub fn that are wrappers now use the do_func_name syntax for stdlib alignment. This change will be pushed into 0.3.1.
